name: Electron CI

on: [push]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        node: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install
      run: |
        cd server
        npm install
    - name: Build (webpack)
      run: |
        cd server
        npm run build-webpack
    - name: Build (windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd server
        npm run build-win
    - name: Build (mac)
      if: matrix.os == 'macOS-latest'
      run: |
        cd server
        npm run build-mac
    - name: Build (linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd server
        npm run build-linux
    - name: Deploy
      if: matrix.node == '12.x'
      env:
        TARGET_OS: ${{ matrix.os }}
      run: |
        cd server
        npm run deploy
    - name: Upload
      if: matrix.node == '12.x'
      env:
        TARGET_OS: ${{ matrix.os }}
        MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
        SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }}
      run: |
        cd server
        npm run upload
    - name: Latest Publish
      if: matrix.node == '12.x'
      env:
        JOB_CONTAINER_ID: ${{ job.container.id }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OWNER: TakenokoTech
        REPO: ScreenMirrorAndroid
        TARGET_OS: ${{ matrix.os }}
      run: |
        cd server/build
        node ../ci/release.js
