name: Electron CI

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        cd server
        npm install
    - name: Build (webpack)
      run: |
        cd server
        npm run build-webpack
    - name: Build (windows)
      run: |
        cd server
        npm run build-win
    - name: Build (mac)
      run: |
        cd server
        npm run build-mac
    - name: Build (linux)
      run: |
        cd server
        npm run build-linux
