name: Electron CI

on: [push]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        node: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install
      run: |
        cd server
        npm install
    - name: Build (webpack)
      run: |
        cd server
        npm run build-webpack
    - name: Build (windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd server
        npm run build-win
    - name: Build (mac)
      if: matrix.os == 'macOS-latest'
      run: |
        cd server
        npm run build-mac
    - name: Build (linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd server
        npm run build-linux
    - name: Deploy (windows)
      if: matrix.os == 'windows-latest' && matrix.node == '12.x'
      env:
        TARGET_PATH: 'ScreenMirrorApp-win32-x64'
        MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
        SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }}
      run: |
        cd server
        npm run deploy
        npm run upload
    - name: Deploy (mac)
      if: matrix.os == 'macOS-latest' && matrix.node == '12.x'
      env:
        TARGET_PATH: 'ScreenMirrorApp-darwin-x64'
        MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
        SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }}
      run: |
        cd server
        npm run deploy
        npm run upload
    - name: Deploy (linux)
      if: matrix.os == 'ubuntu-latest' && matrix.node == '12.x'
      env:
        TARGET_PATH: 'ScreenMirrorApp-linux-x64'
        MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
        SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }}
      run: |
        cd server
        npm run deploy
        npm run upload