name: Electron CI

on: [push]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        node: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install
      run: |
        cd server
        npm install
    - name: Build (webpack)
      run: |
        cd server
        npm run build-webpack
    - name: Build (windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd server
        npm run build-win
    - name: Build (mac)
      if: matrix.os == 'macOS-latest'
      run: |
        cd server
        npm run build-mac
    - name: Build (linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd server
        npm run build-linux
