name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Debug Build
        run: |
          chmod +x ./gradlew && ./gradlew assembleDebug

  deploy_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Release Build
        run: |
          chmod +x ./gradlew && ./gradlew assembleRelease
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      - name: Upload DeployGate
        env:
          JOB_CONTAINER_ID: ${{ job.container.id }}
          DEPLOYGATE_USER: ${{ secrets.DEPLOYGATE_USER }}
          DEPLOYGATE_API_KEY: ${{ secrets.DEPLOYGATE_API_KEY }}
        run: |
          cd app/build/outputs/apk/release
          curl -f -F "file=@app-release.apk" -F "token=${DEPLOYGATE_API_KEY}" -F "message=${JOB_CONTAINER_ID} is build" "https://deploygate.com/api/users/${DEPLOYGATE_USER}/apps"
          if [ $? != 0 ]; then exit 1 ;fi
